### ISSUE TITLE
kifield doesn't handle double-quote character correctly

### ISSUE THREAD

**Issue by ppelleti** [xesscorp/KiField#35] opened 2017-11-08 00:43 UTC
Given the following `.sch` and `.xlsx` files:

[kifield-trouble.zip](https://github.com/xesscorp/KiField/files/1452188/kifield-trouble.zip)

After running the following command:

```
kifield -x DaysToXmas.xlsx -i DaysToXmas.sch
```

The resulting `.sch` file ends up with lines like this:

```
F 4 "11 Position Header Connector 0.100" (2.54mm) Through Hole Gold" H 3950 6950 50 0001 C CNN "description"
```

which EESchema then interprets as being a field named ` H 3950 6950 50 0001 C CNN `.

**Comment by xesscorp** [comment] 2017-12-31 15:36
Thanks for the detailed error report. The problem was caused by mishandling of escaped quotation marks inside a quoted string. Fixed in kifield 0.1.9.

**Closed by xesscorp** 2017-12-31 15:36 UTC
